all:
#	perl parse.pl geophotoshow.org.js ..\geophotoshow\scripts\geophotoshow.js
#	java -jar ../yuicompressor-2.3.5.jar -o ..\geophotoshow\scripts\geophotoshow-min.js ..\geophotoshow\scripts\geophotoshow.js
	perl parse.pl flickrgmapshow.user.org.js ../flickr_gmap_show.user.js
	java -jar ../yuicompressor-2.3.5.jar -o ../flickrgmapshow.user-min.js ../flickrgmapshow.user.js

#	perl copytoallgm.pl ..\flickr_gmap_show.user.js
